{
    "name": "Gedeelde Weelde Connection Coin",
    "version": "16.0.1.1.0",
    "category": "Point of Sale",
    "summary": "Connection Coin for Gedeelde Weelde",
    "author": "Gedeelde Weelde",
    "website": "https://github.com/Gedeelde-Weelde/dutch-food-coop-odoo",
    "license": "AGPL-3",
    "depends": [
        "point_of_sale",
        "pos_discount",
        "contacts",
        "partner_firstname",
        "mail",
    ],
    "assets": {
        "point_of_sale.assets": [
            "gw_connection_coin/static/src/css/partner_list_screen.css",
            "gw_connection_coin/static/src/js/discount_button.js",
            "gw_connection_coin/static/src/js/connection_coin_utils.js",
            "gw_connection_coin/static/src/js/barcode_handler.js",
            "gw_connection_coin/static/src/js/partner_list_screen.js",
            "gw_connection_coin/static/src/js/customer_facing_display.js",
            "gw_connection_coin/static/src/xml/partner_list_screen.xml",
            "gw_connection_coin/static/src/xml/customer_facing_display.xml",
            "gw_connection_coin/static/src/xml/selection_popup.xml",
        ],
    },
    "data": [
        "security/ir.model.access.csv",
        "views/res_partner_views.xml",
        "views/product_template_views.xml",
        "views/res_config_settings_views.xml",
        "wizard/connection_coin_wizard_views.xml",
        "report/connection_coin_report.xml",
        "data/mail_template_data.xml",
        "data/ir_cron_data.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
